### ISSUE TITLE
No output generated and Pandoc msg "--smart/-S has been removed"

### ISSUE THREAD

**Issue by adegutis** [dfinke/ConvertFromMarkdown#1]
I am not getting an output file. I created the following md file named test1.md (note: I am using the single quotes instead of the backticks for the code blocks only in this Issue posting, not in my actual test1.md file, so that Github doesn't try to interpret it; not sure if there's a better way to include backticks when submitting issues):

```
<!-- Chapter Start -->

# Test 1

'''ps
$a = 'string'
$a
'''

<!-- Chapter End -->

<!-- Chapter Start -->

# Test 2

'''ps
$num = 3
$num
'''

<!-- Chapter End -->
```

Running the command `ConvertFrom-Markdown -markdownFile .\test1.md -outputPath .\ -OutputType PDF` returns the following:

all analyzed - no issues
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc.exe --help for more information.

I get the same message whether I use HTML, DOCX or PDF as the OutputType.
The Book,txt and chapter##.txt files are being created in the manifest folder.

Here is the version info:
pandoc --v
pandoc.exe 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2

$psversiontable

| Name |                           Value
|-----|-----
| PSVersion |                      5.1.16299.611
| PSEdition   |                   Desktop
| PSCompatibleVersions |          {1.0, 2.0, 3.0, 4.0...}
BuildVersion  |                 10.0.16299.611
| CLRVersion    |                 4.0.30319.42000
| WSManStackVersion |             3.0
| PSRemotingProtocolVersion |     2.3
| SerializationVersion   |        1.1.0.1

**Comment by dfinke** [comment]
Thanks for the issue. 

The `pandoc` parameters are set here.

https://github.com/dfinke/ConvertFromMarkdown/blob/master/ConvertFromMarkdown.psm1#L30

I have `pandoc` < 2.0. If you want you can tweak those params for now, until I have a chance to test and publish. Maybe a `map` could be created and before `pandoc` is run is can choose the correct parameter set.

**Comment by indig0fox** [comment]
Running pandoc 2.10, modifying ConvertFromMarkdown.psm1 > Line 52 by removing the -S flag fixes this. The code already has the extension determined by the parameterized $outputType variable included with the $outFile string, so pandoc knows what format to output based on that.

Thank you for the module.
