### ISSUE TITLE
pandoc.exe reports "-S has been removed"

### ISSUE THREAD

**Issue by janegilring** [dfinke/ConvertFromMarkdown#2]
When running ConvertFrom-Markdown after installing the latest version of pandoc (2.3.1), I get this error message:
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc.exe --help for more information.

**Comment by janegilring** [comment]
Sorry for creating a duplicate issue, I`ll close this one.
For now, I removed -S to make it run.

**Comment by dfinke** [comment]
Thanks, what's the version of pandoc that you have installed?

**Comment by janegilring** [comment]
2.3.1

**Comment by dfinke** [comment]
Thanks!
